name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"


concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ runner.os }}-11ty-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-11ty
      - run: npm ci
      - run: npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
